name: test personal license
on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**.md"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - macos-10.15
          - macos-11.0
          - windows-2019
        unity-version:
          - 2018.4.1f1
          - 2019.4.1f1
          - 2020.1.0f1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup unity
        uses: kuler90/setup-unity@v1
        with:
          unity-version: ${{ matrix.unity-version }}
      - name: Activate unity
        uses: ./
        with:
          unity-username: ${{ secrets.UNITY_USERNAME }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}
          unity-authenticator-key: ${{ secrets.UNITY_AUTHENTICATOR_KEY }}
